app/javascript/controllers/hello_controller.js
app/javascript/controllers/index.js
app/javascript/packs/application.js
package.json
yarn.lock

Adding Stimulus.
Command used:
```sh
rails webpacker:install:stimulus
```

Adding stimulus.js to the project

---

app/controllers/bars_controller.rb
app/models/bar.rb
app/views/bars/edit.html.erb
app/views/bars/index.html.erb
app/views/bars/new.html.erb
app/views/bars/show.html.erb
config/routes.rb
db/migrate/20200217150657_create_bars.rb
db/migrate/20200217160453_add_reference_user_to_bars.rb
db/schema.rb
db/seeds.rb
test/controllers/bars_controller_test.rb
test/models/bar_test.rb

What we did:
- Created the `Bar` model
- Put some validations on presence and uniqueness of concerned fields
- Created the `bars` controller
- Tested all views by ensuring we had access to our instance variables and `create` and `update` routes worked
- Created a couple seeds

Created the bar model, its controller and tested all views

---

Gemfile
Gemfile.lock
db/seeds.rb

A seed for our DB.
To be changed when User will be more complete.
to use it:
```sh
rails db:reset
```

Created seed

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button.scss
app/javascript/custom/button.js
app/javascript/packs/application.js
app/views/components/_button.html.erb
app/views/components/_button_link.html.erb

- New button component based on a button
- New button component based on a link
Both are just the same and just one colored for now, an option to chose the color can be added.
(Gif de mauvaise qualité 😳)

Button component

---

.gitignore
Gemfile
Gemfile.lock
app/models/bar.rb
app/models/user.rb
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20200218111121_create_active_storage_tables.active_storage.rb
db/schema.rb

Cloudinary set up done :
- création du fichier .env + .gitignore
- installation de la gem cloudinary 
- ajout de l'URL cloudinary dans .env
- création des 2 tables dans la database 
- ajout de cloudinary dans le storage
- update de la config dans l'environnement development + production 
- ajout sur la class User : has_one_attached :photo
- ajout sur la class Bar : has-many_attached :photos

Cloudinary set up

---

app/assets/stylesheets/components/_navbar.scss
app/views/bars/index.html.erb
app/views/components/_navbar.html.erb
app/views/layouts/application.html.erb

Navbar can work on any page now. Dark + Light Theme

---

app/views/components/_navbar.html.erb

Signup and Signing on Home page

Sign-in links on Home

---

app/controllers/pages_controller.rb
app/helpers/gravatar_helper.rb
app/views/components/_avatar.html.erb
app/views/components/_navbar.html.erb

Avatar created. Integrated to Nav Bar

---

app/views/bars/index.html.erb
app/views/components/_navbar.html.erb

link to create a bar

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_home.scss
app/views/bars/index.html.erb
app/views/components/_bar_card.html.erb
app/views/pages/home.html.erb

Added a banner on top bars and revamped the card design for a slick homepage
Before:
After:

Revamped the homepage banner for top bars

---

app/assets/stylesheets/components/_form.scss
app/views/bars/new.html.erb

Changement de couleur de fond à blanc pour le site
Seulement la couleur purple est appliquée pour le form
Changement du nom de la class marc en background-form

changes on background color

---

app/assets/stylesheets/components/_card.scss
app/views/bars/index.html.erb

Changed the display of cards in bars index

---

app/javascript/controllers/total_price_controller.js
app/views/bars/show.html.erb

New pricing dynamic by number of guests

Dynamic pricing on the bar show

---

db/places.json
db/seeds.rb

Improved seeds:
- Real bars
- Capacity is a multiple of 10
- Dates are recent (from 2 weeks ago to in 2 weeks) and coherent (same booking date, hours between opening hours)
- States are up to date and coherent with dates (past bookings are "Terminé", others are "À venir" or "Annulé" with a probable 20% cancellation rate)

Real seeds

---

app/assets/stylesheets/components/_booking_form.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_bar_show.scss
app/controllers/bookings_controller.rb
app/javascript/controllers/flatpickr_controller.js
app/javascript/controllers/pick_date_controller.js
app/views/bars/_booking_form.html.erb
app/views/bars/show.html.erb
app/views/components/_button.html.erb
app/views/layouts/application.html.erb

- Pick up date and hours
- Design
- Fully functional
- Changed the button component for it to submit forms

Booking form

---

app/assets/stylesheets/components/_map.scss
app/views/bars/_info_window.html.erb

Changement du style des pop up / cards qui s'affichent quand on clique sur un marker sur la map

Card on map

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_review_form.scss
app/assets/stylesheets/pages/_bar_show.scss
app/assets/stylesheets/pages/_booking_show.scss
app/controllers/bookings_controller.rb
app/controllers/reviews_controller.rb
app/policies/booking_policy.rb
app/policies/review_policy.rb
app/views/bookings/_review_form.html.erb
app/views/bookings/show.html.erb
config/application.rb
config/locales/fr.yml
config/routes.rb
db/migrate/20200220152859_add_cancelled_by_to_reviews.rb
db/migrate/20200220153020_remove_cancelled_by_from_reviews.rb
db/migrate/20200220153055_add_cancelled_by_to_bookings.rb
db/schema.rb

- Implemented a booking show
If you're a owner: You can cancel the booking and email the renter for an upcoming booking
If you're a renter:
- You can cancel the booking and email the renter for an upcoming booking
- You can review a finished booking, you can access your review

Booking show

---

app/javascript/controllers/guest_count_controller.js
app/javascript/controllers/total_price_controller.js
app/views/bars/show.html.erb

Now that the booking form is finished, we could improve the JS a little for the Total Price.
(Sorry @dornby your code was magnificent)

Improved the total price counter

---

app/assets/stylesheets/components/_navbar.scss
app/views/components/_navbar.html.erb

Buttons on the navbar

---

db/schema.rb
db/seeds.rb

Canceled by seeds

---

app/assets/stylesheets/components/_navbar.scss

white name and arrow on homepage : https://share.getcloudapp.com/2NuBxOrl

Avatar link

---

app/controllers/bars_controller.rb
app/models/user.rb
app/policies/bar_policy.rb
app/views/bars/owner_index.html.erb
config/routes.rb

Crude Owner Bars first version

---

app/controllers/bars_controller.rb
app/helpers/smart_units_helper.rb
app/models/bar.rb
app/views/bars/index.html.erb
app/views/components/_bar_card.html.erb

implementation distance between address and bar

---

app/controllers/bookings_controller.rb

Correction on typo on booking state

---

app/assets/stylesheets/components/_dashboard_menu.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_signin.scss
app/policies/bar_policy.rb
app/views/components/_footer.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb

J'ai :
- enlevé l'espace blanc tout en bas du footer
- debug la supperposition du footer et des cards sur le dashboard
- mis du style sur le form de la page "Forgot your password" = password / edit

debug de : footer + forgot password + edit bar

---

app/assets/stylesheets/pages/_dashboard_bookings.scss
app/views/bookings/show.html.erb

Ajout du Sidemenu sur la page Dashboard/show  + adaptation avec le contenu déjà existant

Dashboard change

---

app/assets/stylesheets/components/_dashboard_cards.scss
app/assets/stylesheets/components/_dashboard_menu.scss
app/assets/stylesheets/components/_dashboard_oneliner_cards.scss
app/assets/stylesheets/components/_index.scss
app/controllers/bars_controller.rb
app/controllers/bookings_controller.rb
app/policies/booking_policy.rb
app/views/bars/owner_index.html.erb
app/views/bookings/_bookings_list.html.erb
app/views/bookings/owner_index.html.erb
app/views/components/_dashboard_menu.html.erb
app/views/components/_dashboard_oneliner_cards.html.erb
app/views/components/_navbar.html.erb
app/views/layouts/application.html.erb
config/routes.rb

- New component for small details
- Clicking on a small cards leads to the Bookings#show
- Shares a lot of code with the normal bookings index

Dashboard bars + Booking Details on the bar side

---

app/assets/stylesheets/components/_map.scss

hide the search bar in the map

---

app/assets/stylesheets/components/_carousel.scss
app/javascript/custom/carousel.js

https://share.getcloudapp.com/nOuNYvn7

No dots and white border on carousel

---

app/assets/stylesheets/components/_card.scss
app/views/components/_bar_card.html.erb

https://share.getcloudapp.com/z8uXqrLp

One liner price

---

app/assets/stylesheets/application.scss
app/models/bar.rb
app/views/bars/new.html.erb
app/views/bars/show.html.erb
app/views/bookings/_review_form.html.erb

Validations des photos avant la creation du formulaire
Aligner Back et edit sur la show

Edit create bar

---

app/assets/stylesheets/application.scss
app/views/bookings/_review_form.html.erb

change in french

---

app/assets/stylesheets/components/_navbar.scss

As it was at the beginning: black on the home (green links)
White on the other pages (red links)
No hover, no blue border on click.

Fixed the links template in the menu bar and the drop down

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/views/bookings/show.html.erb

bug sur la date en anglais et sur l'heure qui était décalée

bug date resolved
